services:

  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx/https.conf.template:/etc/nginx/https.conf.template
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/entrypoint.sh:/entrypoint.sh
    entrypoint: [ "sh", "-c", "/entrypoint.sh" ]
    environment:
      NGINX_PORT: ${NGINX_PORT:-80}
      NGINX_HTTPS_ENABLED: ${NGINX_HTTPS_ENABLED:-false}
      NGINX_SSL_PORT: ${NGINX_SSL_PORT:-443}
      NGINX_SSL_CERT_FILENAME: ${NGINX_SSL_CERT_FILENAME:-phpbe.crt}
      NGINX_SSL_CERT_KEY_FILENAME: ${NGINX_SSL_CERT_KEY_FILENAME:-phpbe.key}
    depends_on:
      - phpbe
    ports:
      - "${EXPOSE_NGINX_PORT:-80}:${NGINX_PORT:-80}"
      - "${EXPOSE_NGINX_SSL_PORT:-443}:${NGINX_SSL_PORT:-443}"


  phpbe:
    image: phpbe/be:latest
    restart: always
    depends_on:
      - mysql
      - redis
    volumes:
      # 挂载 php 目录
      - ./volumes/phpbe/data:/phpbe/data
      - ./volumes/phpbe/www:/phpbe/www


  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${POSTGRES_PASSWORD:-phpbe@123456}
    volumes:
      # 挂载 MySQL 持久化目录
      - ./volumes/mysql/data:/var/lib/mysql


  redis:
    image: redis:6-alpine
    restart: always
    volumes:
      # 挂载 REDIS 持久化目录
      - ./volumes/redis/data:/data
    # 设置 Redis 密码
    command: redis-server --requirepass ${REDIS_PASSWORD:-phpbe@123456}
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]

