<?php

namespace Be\AdminPlugin\Exporter;

use PhpOffice\PhpSpreadsheet\Cell\Coordinate;
use PhpOffice\PhpSpreadsheet\IOFactory;
use PhpOffice\PhpSpreadsheet\Spreadsheet;

class Excel extends Driver
{

    private $started = false;

    /**
     * @var Spreadsheet
     */
    private $handler = null;

    // 行号
    private $index = 0;

    // 输出格式 Excel5 : xls / Excel2007 : xlsx
    private $xlsType = 'Xls';

    /**
     * 准备导出
     * @return Driver
     */
    public function start()
    {
        if (!$this->started) {
            $this->started = true;
            session_write_close();
            set_time_limit($this->timeLimit);
            ini_set('memory_limit', $this->memoryLimit);

            $filename = null;
            if ($this->outputFileNameOrPath !== null) {
                $filename = $this->outputFileNameOrPath;
                if (strrchr(strtolower($filename), '.') === 'xlsx') {
                    $this->xlsType = 'xlsx';
                }
            } else {
                $filename = date('YmdHis') . '.xls';
            }

            if ($this->outputType === 'http') {
                header("Content-Type: application/vnd.ms-excel");
                header('Content-Disposition: attachment; filename=' . $filename);
                header('Pragma:no-cache');
            }

            $this->handler = new Spreadsheet();

            $this->handler->getProperties()
                ->setCreator("Be")
                ->setLastModifiedBy("Be")
                ->setTitle("Generated by Be Framework")
                ->setSubject("Generated by Be Framework")
                ->setDescription('Generated by Be Framework')
                ->setKeywords("Generated by Be Framework")
                ->setCategory("Generated by Be Framework");

            $this->handler->setActiveSheetIndex(0);

            $activeSheet = $this->handler->getActiveSheet();

            $sheetName = $filename;
            $pos = strrpos($filename, '.');
            if ($pos !== false) {
                $sheetName = substr($filename, 0, $pos);
            }

            $activeSheet->setTitle($sheetName);
        }

        return $this;
    }

    /**
     * 设置表格头
     *
     * @param array $headers
     * @return Driver
     */
    public function setHeaders($headers = [])
    {
        if (!$this->started) {
            $this->start();
        }

        $this->index++;

        $activeSheet = $this->handler->getActiveSheet();

        $col = 1;
        foreach ($headers as $header) {
            $colName = Coordinate::stringFromColumnIndex($col);
            $cellName = $colName. $this->index;
            $activeSheet->setCellValue($cellName, $header);
            $col++;
        }

        // 表头样式
        $style = array(
            'font' => array(
                'bold' => true
            ),
        );

        $colName = Coordinate::stringFromColumnIndex($col - 1);
        $activeSheet->getStyle('A'.$this->index.':'. $colName .$this->index)->applyFromArray($style);
        return $this;
    }

    /**
     * 添加一行数据
     *
     * @param array $row
     * @return Driver
     */
    public function addRow($row = [])
    {
        if (!$this->started) {
            $this->start();
        }

        $this->index++;

        $activeSheet = $this->handler->getActiveSheet();

        $col = 1;
        foreach ($row as $x) {
            $colName = Coordinate::stringFromColumnIndex($col);
            $cellName = $colName . $this->index;
            $activeSheet->setCellValue($cellName, $x);
            $col++;
        }

        return $this;
    }


    /**
     * 结束输出，收尾
     *
     * @return Driver
     */
    public function end() {

        $writer = IOFactory::createWriter($this->handler, $this->xlsType);

        if ($this->outputType === 'http') {
            $writer->save('php://output');
        } else {
            $writer->save($this->outputFileNameOrPath);
        }

        return $this;
    }

}